#!/usr/bin/env bash

#unit tests
#TODO: gcp specific tests
cd java
mvn test -q -Dgroups=gcp
cd ..

#e2e operator tests
#Deploy operator
kubectl create clusterrolebinding my-user-role-binding --clusterrole=cluster-admin --user=${SERVICE_ACCOUNT} && kubectl apply -f examples/common/rbac-bundle.yaml

kubectl get pods --selector=k8s-app=cassandra-operator | tee | awk 'NR>1{if($3 == "CrashLoopBackOff") {exit 1}}'
