#!/usr/bin/env bash

#unit tests
#TODO: gcp specific tests

helm install -f ~/cassandra-operator/test/testGCPCassandraValues.yaml -n cassandra-default --wait ~/cassandra-operator/helm/cassandra
kubectl get pods
sleep 180
kubectl get pods

export CASSANDRA_CLUSTER=cassandra-default

cd ~/cassandra-operator/java
telepresence --method inject-tcp --run mvn test -q -Dgroups=integration -DcassandraCluster=cassandra-default-seeds
cd ~/cassandra-operator/test
