#!/usr/bin/env bash

#unit tests
#TODO: pivotal specific tests
mvn test -q -Dgroups=pivotal


#e2e operator tests
#Deploy operator
kubectl create clusterrolebinding my-user-role-binding --clusterrole=cluster-admin --user=${SERVICE_ACCOUNT} && kubectl apply -f bundle.yaml

kubectl get pods --selector=k8s-app=cassandra-operator | tee | awk 'NR>1{if($3 == "CrashLoopBackOff") {exit 1}}'
