#!/bin/bash

set -xue

# dagi -- docker apt-get install
# a simple script to install packages without traces

if [ ${1} == "file" ]; then
  apt-get update
  apt-get -qy --no-install-recommends ${APT_GET_OPTS:-} install -f ${2}
  rm -rf /var/lib/apt/lists/*
else
  apt-get update
  DEBIAN_FRONTEND=noninteractive apt-get -qy --no-install-recommends ${APT_GET_OPTS:-} install $@
  rm -rf /var/lib/apt/lists/*
fi