apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: cassandrabackups.cassandraoperator.instaclustr.com
spec:
  additionalPrinterColumns:
  - JSONPath: .globalStatus
    description: Restore operation status
    name: Status
    type: string
  - JSONPath: .globalProgress
    description: Restore operation progress
    name: Progress
    type: string
  group: cassandraoperator.instaclustr.com
  names:
    kind: CassandraBackup
    listKind: CassandraBackupList
    plural: cassandrabackups
    singular: cassandrabackup
  scope: Namespaced
  subresources: {}
  validation:
    openAPIV3Schema:
      description: CassandraBackup is the Schema for the cassandrabackups API
      properties:
        apiVersion:
          description: 'APIVersion defines the versioned schema of this representation
            of an object. Servers should convert recognized schemas to the latest
            internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
          type: string
        globalProgress:
          type: string
        globalStatus:
          type: string
        justCreate:
          type: boolean
        kind:
          description: 'Kind is a string value representing the REST resource this
            object represents. Servers may infer this from the endpoint the client
            submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
          type: string
        metadata:
          type: object
        spec:
          description: CassandraBackupSpec defines the desired state of CassandraBackup
          properties:
            cdc:
              type: string
            cluster:
              type: string
            concurrentConnections:
              type: integer
            createMissingBucket:
              type: boolean
            datacenter:
              description: Cassandra DC name to back up. Used to find the pods in
                the CDC
              type: string
            entities:
              type: string
            globalRequest:
              type: boolean
            insecure:
              type: boolean
            metadataDirective:
              type: string
            secret:
              type: string
            skipBucketVerification:
              type: boolean
            snapshotTag:
              description: The snapshot tag for the backup
              type: string
            storageLocation:
              description: The uri for the backup target location e.g. s3 bucket,
                filepath
              type: string
          required:
          - cdc
          - cluster
          - datacenter
          - snapshotTag
          - storageLocation
          type: object
        status:
          items:
            description: CassandraBackupStatus defines the observed state of CassandraBackup
            properties:
              node:
                description: name of pod / node
                type: string
              progress:
                description: Progress shows the percentage of the operation done
                type: string
              state:
                description: State shows the status of the operation
                type: string
            required:
            - node
            - progress
            - state
            type: object
          type: array
      required:
      - spec
      type: object
  version: v1alpha1
  versions:
  - name: v1alpha1
    served: true
    storage: true
