apiVersion: stable.instaclustr.com/v1
kind: CassandraDataCenter
metadata:
  name: test-dc
spec:
  replicas: 3
  sidecarImage: "gcr.io/cassandra-operator/cassandra-sidecar:latest"
  cassandraImage: "gcr.io/cassandra-operator/cassandra:latest"
  imagePullPolicy: IfNotPresent
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 512Mi
  dataVolumeClaim:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  privilegedSupported: true
  prometheusSupport: false
