apiVersion: stable.instaclustr.com/v1
kind: CassandraDataCenter
metadata:
  name: test-dc
spec:
  replicas: 5 
  sidecarImage: "gcr.io/cassandra-operator/cassandra-sidecar:latest"
  cassandraImage: "gcr.io/cassandra-operator/cassandra:3.11.3"
  imagePullPolicy: Always
  resources:
    limits:
      memory: 1Gi
    requests:
      memory: 1Gi
  dataVolumeClaim:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 100Mi
  privilegedSupported: true
  prometheusSupport: false
