apiVersion: stable.instaclustr.com/v1
kind: CassandraBackup
metadata:
  name: backup-now37
spec:
  selector:
    matchLabels:
      cassandra-operator.instaclustr.com/datacenter: backup3-cassandra
  backupType: "AWS_S3"
  target: "kube-backup-test-cassandra"
