apiVersion: apps/v1beta2
kind: Deployment
metadata:
  labels:
    k8s-app: cassandra-operator
  name: cassandra-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: cassandra-operator
  template:
    metadata:
      labels:
        k8s-app: cassandra-operator
    spec:
      containers:
      - image: gcr.io/cassandra-operator/cassandra-operator:latest
        name: cassandra-operator
        ports:
        - containerPort: 8080
          name: http
        resources:
          limits:
            cpu: 200m
            memory: 100Mi
          requests:
            cpu: 100m
            memory: 50Mi
      securityContext:
        runAsNonRoot: true
        runAsUser: 65534