---
# Source: cassandra-operator/templates/serviceaccount.yaml

apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    app: cassandra-operator
  name: cassandra-operator
---
# Source: cassandra-operator/templates/clusterrole.yaml

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: cassandra-operator
  name: cassandra-operator
rules:
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - stable.instaclustr.com
  resources:
  - cassandra-cluster
  - cassandra-clusters
  - cassandra-datacenter
  - cassandra-datacenters
  - cassandra-backup
  - cassandra-backups
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs: ['*']
- apiGroups: ['']
  resources:
  - configmaps
  - secrets
  verbs: ['*']
- apiGroups: ['']
  resources:
  - pods
  verbs: ['list', 'delete']
- apiGroups: ['']
  resources:
  - services
  - endpoints
  - persistentvolumeclaims
  - persistentvolumes
  verbs: ['get', 'create', 'update', 'delete', 'list']
- nonResourceURLs: ["/version", "/version/*"]
  verbs: ['get']
- apiGroups: ['']
  resources:
  - nodes
  verbs: ['list', 'watch']
- apiGroups: ['']
  resources:
  - namespaces
  verbs: ['list']

---
# Source: cassandra-operator/templates/clusterrolebinding.yaml

apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  labels:
    app: cassandra-operator
  name: cassandra-operator
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: cassandra-operator
subjects:
- kind: ServiceAccount
  name: cassandra-operator
  namespace: default
---
# Source: cassandra-operator/templates/deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cassandra-operator
    operator: cassandra
  name: cassandra-operator
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cassandra-operator
      operator: cassandra
      release: cassandra-operator
  template:
    metadata:
      labels:
        app: cassandra-operator
        operator: cassandra
        release: cassandra-operator
    spec:
      containers:
        - name: cassandra-operator
          image: "gcr.io/cassandra-operator/cassandra-operator:latest"
          imagePullPolicy: "IfNotPresent"
          ports:
            - containerPort: 8080
              name: http
          resources:
            {}

      serviceAccountName: cassandra-operator
