---
# Source: cassandra/templates/cassandra.yaml
apiVersion: stable.instaclustr.com/v1
kind: CassandraDataCenter
metadata:
  name: test-dc-cassandra
  labels:
    app: cassandra
spec:
  replicas: 5
  cassandraImage: "gcr.io/cassandra-operator/cassandra:3.11.3"
  sidecarImage: "gcr.io/cassandra-operator/cassandra-sidecar:latest"
  imagePullPolicy: IfNotPresent
  imagePullSecret: ""
  resources:
    limits:
      memory: 1Gi
    requests:
      memory: 1Gi

  dataVolumeClaim:
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 500Mi

  prometheusSupport: false
  privilegedSupported: true
