#!/usr/bin/env bash
# at the point a makefile is probably the sensible choice
set -o errexit
set -o nounset
set -o pipefail

cd `dirname "$BASH_SOURCE"`/..

source ./buildenv/repo

make

if [[ "${CIRCLE_BRANCH}" == master ]]; then
    docker tag cassandra-operator:latest "${REGISTRY}/cassandra-operator:${TAG}"
    docker tag cassandra-operator:latest "${REGISTRY}/cassandra-operator:latest"
    docker tag cassandra-sidecar:latest "${REGISTRY}/cassandra-sidecar:${TAG}"
    docker tag cassandra-sidecar:latest "${REGISTRY}/cassandra-sidecar:latest"
    docker tag cassandra:latest "${REGISTRY}/cassandra:latest"
    docker tag cassandra:3.11.5 "${REGISTRY}/cassandra:3.11.5"
fi
