#!/usr/bin/env bash
# at the point a makefile is probably the sensible choice
set -o errexit
set -o nounset
set -o pipefail

cd $(dirname "$BASH_SOURCE")/..

source ./buildenv/repo

make

function release_dev() {
  docker tag cassandra-operator:latest "${REGISTRY}/cassandra-operator:latest-dev"
  docker tag instaclustr-icarus:latest "${REGISTRY}/instaclustr-icarus:latest-dev"
  docker tag cassandra-3.11.8:latest "${REGISTRY}/cassandra-3.11.8:latest-dev"
  docker tag cassandra-4.0-beta2:latest "${REGISTRY}/cassandra-4.0-beta2:latest-dev"
}

function release_prod() {
  docker tag cassandra-operator:latest "${REGISTRY}/cassandra-operator:${TAG}"
  docker tag cassandra-operator:latest "${REGISTRY}/cassandra-operator:latest"
  docker tag instaclustr-icarus:latest "${REGISTRY}/instaclustr-icarus:${TAG}"
  docker tag instaclustr-icarus:latest "${REGISTRY}/instaclustr-icarus:latest"
  docker tag cassandra-3.11.8:latest "${REGISTRY}/cassandra-3.11.8:${TAG}"
  docker tag cassandra-3.11.8:latest "${REGISTRY}/cassandra-3.11.8:latest"
  docker tag cassandra-4.0-beta2:latest "${REGISTRY}/cassandra-4.0-beta2:${TAG}"
  docker tag cassandra-4.0-beta2:latest "${REGISTRY}/cassandra-4.0-beta2:latest"
}

if [ "${1}" = "dev" ]; then
  release_dev
elif [ "${1}" = "prod" ]; then
  release_prod
fi
