#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

#try to resolve buildenv dir then set working directory to git repo root
cd `dirname "$BASH_SOURCE"`/..

source ./buildenv/repo

echo "Building ${REGISTRY}:${TAG}"

docker build --tag "${REGISTRY}:${TAG}" --tag "${REGISTRY}:latest" --tag "$1" docker/${1} 1>/dev/null
