#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

#try to resolve buildenv dir then set working directory to git repo root
cd `dirname "$BASH_SOURCE"`/..

source ./buildenv/repo

(source ./buildenv/repo && cd docker && C_IMAGE_VERSION=1.0.0 make cassandra)
(source ./buildenv/repo && cd docker && C_IMAGE_VERSION=4.0.1 make cassandra-4)