#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

#try to resolve buildenv dir then set working directory to git repo root
cd `dirname "$BASH_SOURCE"`/..

source ./buildenv/repo

echo "Building Cassandra versions in version list"
while IFS="" read -r line || [[ -n "$line" ]]; do
    echo "Building ${REPO}:${line}"
    docker build --tag "${REPO}:${line}" --tag "${1}:${line}" --build-arg cassandra_version="${line}" docker/${1} 1>/dev/null
done < buildenv/CASSANDRA_VERSIONS