#!/usr/bin/env bash

cp deploy/crds/*_crd.yaml helm/cassandra-operator/crds \
  && cp deploy/{configmap.yaml,role.yaml,role_binding.yaml} helm/cassandra-operator/templates \
  && cp deploy/cassandra/{psp.yaml,psp_performance.yaml} helm/cassandra/templates