#!/usr/bin/env bash


set -o errexit
set -o nounset
set -o pipefail

function defer {
	docker logout gcr.io
}

if [[ "${DONT_LOGIN}" != "true" ]]; then
    trap defer EXIT

    gcloud docker -a

fi

cd `dirname "$BASH_SOURCE"`/..

source ./buildenv/repo



echo "Pushing Cassandra versions in version list"
while IFS="" read -r line || [[ -n "$line" ]]; do
    echo "Pushing ${REPO}:${line}"
    docker push "${REPO}:${line}"  1>/dev/null
    docker push "${1}:${line}"  1>/dev/null
done < buildenv/CASSANDRA_VERSIONS


#docker push "${REPO}:${TAG}"  1>/dev/null
#docker push "${REPO}:latest"  1>/dev/null