#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

cd `dirname "$BASH_SOURCE"`/..

function defer {
	if [[ $REPO == gcr.io/* ]]; then
		docker logout gcr.io
		export DONT_LOGIN="false"
	fi
}

trap defer EXIT

if [[ $REPO == gcr.io/* ]]; then
	gcloud docker -a
fi

export DONT_LOGIN="true"

./buildenv/release base-openjre
./buildenv/release-cassandra cassandra
./buildenv/release cassandra-sidecar
./buildenv/release cassandra-operator
