#!/usr/bin/env bash


set -o errexit
set -o nounset
set -o pipefail

function defer {
	if [[ $REGISTRY == gcr.io/* ]]; then
		docker logout gcr.io
	fi
}

if [[ "${DONT_LOGIN}" != "true" ]]; then
    trap defer EXIT

    gcloud docker -a

fi

cd `dirname "$BASH_SOURCE"`/..

source ./buildenv/repo

docker push "${REGISTRY}:${TAG}"  1>/dev/null
docker push "${REGISTRY}:latest"  1>/dev/null
