#!/usr/bin/env bash

# you can override REGISTRY and TAG if needed

REGISTRY="${REGISTRY:-gcr.io/cassandra-operator}"
CIRCLE_TAG="${CIRCLE_TAG:-}"
NO_DEV="${NO_DEV:-}"
CIRCLE_BRANCH="${CIRCLE_BRANCH:-}"
export REGISTRY="$REGISTRY"

SHA1=$(git rev-parse --short HEAD)
export TAG="${TAG:-${SHA1}}"
