#!/usr/bin/env bash

# you can over ride REPO and TAG if needed

REPO="${REPO:-gcr.io/cassandra-operator}"
CIRCLE_TAG="${CIRCLE_TAG:-}"
CIRCLE_BRANCH="${CIRCLE_BRANCH:-}"
export REPO="$REPO/${1}"

if [[ "${CIRCLE_TAG}" == "" ]] && [[ "${CIRCLE_BRANCH}" != master ]]; then
	export REPO="${REPO}-dev"
fi

SHA1=`git rev-parse --short HEAD`
export TAG="${TAG:-${SHA1}}"