#!/bin/bash -ue

params=""
if [[ -e /var/lib/cassandra/tls/jmx-params ]]; then
    # guess cluster is secure
    params=$(cat /var/lib/cassandra/tls/jmx-params)
fi

if [ "${1-unset}" == "backup" ] || [ "${1-unset}" == "restore" ]; then
    cassandra-backup-restore ${params} $@
    exit $?
else
    cassandra-sidecar ${params} $@
fi