apiVersion: cassandraoperator.instaclustr.com/v1alpha1
kind: CassandraBackup
metadata:
  name: test-cassandra-backup
  labels:
    app: cassandra
spec:
  cdc: test-dc-cassandra
  storageLocation: "s3://stefan-cassandra-testdc-bucket"
  snapshotTag: "mySnapshotTag"
