#!/bin/bash -xue

# overlay configuration from configmap mounted volumes into /etc/cassandra
(
for config_directory in "$@"
do
    # k8s configmap volumes are a mess of symlinks -- the find command cleans this up (skip ay dirs starting with ..)

    cd "${config_directory}"
    find -L . -name "..*" -prune -o \( -type f -print0 \) |
        cpio -pmdLv0 /etc/cassandra
done
)

# Set unlimited memory locking only when running with kernel tweaks enabled.
if [[ "${MEMORY_LOCK-unset}" == "true" ]]; then
    ulimit -l unlimited
fi

# check if TLS config is also needed
if [[ -e /var/lib/cassandra/tls/certs/$(hostname)-keystore.p12 ]]; then
   mkdir -p /etc/cassandra/certs

   cassandra_config=/home/cassandra/.cassandra
   mkdir -p ${cassandra_config}

   cp /var/lib/cassandra/tls/certs/* /etc/cassandra/certs/
   cp /var/lib/cassandra/tls/config/* /etc/cassandra/cassandra.yaml.d/
   cp /var/lib/cassandra/tls/env/* /etc/cassandra/cassandra-env.sh.d/
   cp /var/lib/cassandra/tls/cqlshrc ${cassandra_config}/cqlshrc
   chown -R 999:999 ${cassandra_config}
fi

exec /usr/sbin/cassandra
