{{- if .Values.rbacEnable }}
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  labels:
    app: {{ template "cassandra-operator.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version }}
    heritage: {{ .Release.Service }}
    release: {{ .Release.Name }}
  name: {{ template "cassandra-operator.fullname" . }}
rules:
- apiGroups:
  - extensions
  resources:
  - thirdpartyresources
  verbs:
  - '*'
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - '*'
- apiGroups:
  - stable.instaclustr.com
  resources:
  - cassandra-cluster
  - cassandra-clusters
  - cassandra-datacenter
  - cassandra-datacenters
  verbs:
  - '*'
- apiGroups:
  - apps
  resources:
  - statefulsets
  verbs: ['*']
- apiGroups: ['']
  resources:
  - configmaps
  - secrets
  verbs: ['*']
- apiGroups: ['']
  resources:
  - pods
  verbs: ['list', 'delete']
- apiGroups: ['']
  resources:
  - services
  - endpoints
  verbs: ['get', 'create', 'update']
- nonResourceURLs: ["/version", "/version/*"]
  verbs: ['get']
- apiGroups: ['']
  resources:
  - nodes
  verbs: ['list', 'watch']
- apiGroups: ['']
  resources:
  - namespaces
  verbs: ['list']
{{- end }}
