apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: cassandra-clusters.stable.instaclustr.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: stable.instaclustr.com
  # version name to use for REST API: /apis/<group>/<version>
  version: v1
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: cassandra-clusters
    # singular name to be used as an alias on the CLI and for display
    singular: cassandra-cluster
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: CassandraCuster
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - cluster
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            name:
              type: string
