apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: cassandra-datacenters.stable.instaclustr.com
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: stable.instaclustr.com
  # version name to use for REST API: /apis/<group>/<version>
  version: v1
  # either Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: cassandra-datacenters
    # singular name to be used as an alias on the CLI and for display
    singular: cassandra-datacenters
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: CassandraDataCenter
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - cdc
  validation:
    openAPIV3Schema:
      properties:
        spec:
          required:
          - replicas
          - image
          - imagePullPolicy
          properties:
            name:
              type: string
              description: Name of the data center.
            clusterName:
              type: string
              description: Name of the cluster. If null, will default to a generated name.
            replicas:
              type: integer
              minimum: 1
              description: Number of nodes in the data center.
            image:
              type: string
              description: Image to be used for data center.
            imagePullPolicy:
              type: string
              description: Valid values are "Never" "Always" "IfNotPresent".
            resources:
              type: object
              description: the compute resource to construct pod.
            