apiVersion: stable.instaclustr.com/v1
kind: CassandraDataCenter
metadata:
  name: test-dc
spec:
  replicas: 6
  image: instaclustr/k8s-cassandra
  imagePullPolicy: Never
  resources:
    limits:
      memory: 512Mi
    requests:
      memory: 512Mi
  capacity:
    requests:
      storage: 100Mi